name: firebase deploy for Production

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: express-template
  BUILD_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "17.x"

      - name: Nodemodules install
        run: npm install

      - name: Eslint
        run: cd functions && npm run lint

      - name: Jest
        run: cd functions && npm run test

  build_flow:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        env:
          PROD_GCP_SA_KEY: ${{ secrets.PROD_GCP_SA_KEY }}
        if: ${{ env.PROD_GCP_SA_KEY != ''}}
        with:
          python-version: ${{ matrix.python-version }}
          version: latest
          service_account_key: ${{ secrets.PROD_GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install expect command
        run: sudo apt-get install expect
      - name: Install firebase-tools
        run: sudo npm install -g firebase-tools
      - name: deploy to firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.PROD_FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
        if: ${{ env.PROJECT_ID != '' && env.FIREBASE_TOKEN != ''}}
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy --project ${{ secrets.PROD_PROJECT_ID }} -f
  slack_notification:
    runs-on: ubuntu-latest
    needs: build_flow

    steps:
      - name: Notify slack - URLs
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ env.SLACK_WEBHOOK_URL != '' && !failure() }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"${{ github.repository }} Deploy to production\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          curl -X POST --data-urlencode "payload={\"text\": \"デプロイ対象 : ${{ github.sha }}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify slack when failed
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ env.SLACK_WEBHOOK_URL != '' && failure() }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"${{ github.repository }}のデプロイに失敗しました\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
