name: ci/docker Build and Push for Production

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: express-template
  BUILD_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "17.x"

      - name: Nodemodules install
        run: npm install

      - name: Eslint
        run: npm run lint

      - name: Jest
        run: npm run test

  build_flow:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Env Copy
        run: cp .env.sample .env

      - name: Build
        run: docker build -t $IMAGE_NAME:$BUILD_TAG -f ./docker/Dockerfile .

      - name: Tag
        env:
          DOCKER_REGISTRY_NAME: ${{ secrets.DOCKER_REGISTRY_NAME }}
        if: ${{ env.DOCKER_REGISTRY_NAME != ''}}
        run: docker image tag $IMAGE_NAME:$BUILD_TAG ${{ secrets.DOCKER_REGISTRY_NAME }}/$IMAGE_NAME:$BUILD_TAG

      - name: Push
        env:
          DOCKER_REGISTRY_NAME: ${{ secrets.DOCKER_REGISTRY_NAME }}
        if: ${{ env.DOCKER_REGISTRY_NAME != ''}}
        run: docker image push ${{ secrets.DOCKER_REGISTRY_NAME }}/$IMAGE_NAME:$BUILD_TAG

  slack_notification:
    runs-on: ubuntu-latest
    needs: build_flow

    steps:
      - name: Notify slack - URLs
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ env.SLACK_WEBHOOK_URL != '' && !failure() }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"${{ github.repository }} Deploy to production\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          curl -X POST --data-urlencode "payload={\"text\": \"デプロイ対象 : ${{ github.sha }}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify slack when failed
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ env.SLACK_WEBHOOK_URL != '' && failure() }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"${{ github.repository }}のデプロイに失敗しました\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
